# Generated by Django 4.2.6 on 2024-03-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0002_alter_employee_options_alter_employee_name_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modify_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='employee_info.employee', verbose_name='Последние изменения от'),
        ),
    ]
