# Generated by Django 4.2.6 on 2024-03-10 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг')),
                ('email', models.EmailField(max_length=250, verbose_name='Почта')),
                ('project_role', models.CharField(choices=[('DL', 'Разработчик'), ('AL', 'Аналитик'), ('TT', 'Тестировщик')], max_length=3, verbose_name='Должноcть')),
                ('reservation_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Загруженность работника')),
                ('reservation_status', models.CharField(choices=[('CF', 'Принят'), ('UCF', 'Не принят')], default='UCF', max_length=3, verbose_name='Статус')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Работника',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
