# Generated by Django 4.2.6 on 2024-03-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Стоиомсть')),
                ('last_modify_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='прогресс')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('deadline_date', models.DateField(verbose_name='Дата завершения')),
                ('status', models.CharField(choices=[('AL', 'Аналитика'), ('DP', 'Разработка'), ('TT', 'Тестирование'), ('CL', 'Завершен')], default='AL', max_length=4, verbose_name='Статус')),
                ('last_modify_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Последние изменения от')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-id'],
            },
        ),
    ]
