# Generated by Django 4.2.6 on 2024-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='perspective',
            field=models.CharField(choices=[('BAD', 'Неперспективный'), ('NL', 'Нейтральный'), ('GD', 'Перспективный')], default='NL', max_length=3, verbose_name='Перспективность'),
        ),
    ]
